export const FlashDealsData = [
  {
    id: 1,
    off: 21,
    name: "Mi Led Smart Watch",
    star: 4,
    price: 142.2,
    discount: 180.0,
    imageAddress: "/image/flash-4.png",
  },
  {
    id: 2,
    off: 28,
    name: "Iphone 13 Pro Max",
    star: 5,
    price: 108.0,
    discount: 150.0,
    imageAddress: "/image/flash-3.png",
  },
  {
    id: 3,
    off: 15,
    name: "Classic Rolex Watch",
    star: 3,
    price: 297.5,
    discount: 350.0,
    imageAddress: "/image/flash-2.png",
  },
  {
    id: 4,
    off: 25,
    name: "NikeCourt Zoom Vapor Cage",
    star: 4,
    price: 187.5,
    discount: 250,
    imageAddress: "/image/flash-1.png",
  },
  {
    id: 1,
    off: 21,
    name: "Mi Led Smart Watch",
    star: 4,
    price: 142.2,
    discount: 180.0,
    imageAddress: "/image/flash-4.png",
  },
  {
    id: 2,
    off: 28,
    name: "Iphone 13 Pro Max",
    star: 5,
    price: 108.0,
    discount: 150.0,
    imageAddress: "/image/flash-3.png",
  },
  {
    id: 3,
    off: 15,
    name: "Classic Rolex Watch",
    star: 3,
    price: 297.5,
    discount: 350.0,
    imageAddress: "/image/flash-2.png",
  },
  {
    id: 4,
    off: 25,
    name: "NikeCourt Zoom Vapor Cage",
    star: 4,
    price: 187.5,
    discount: 250,
    imageAddress: "/image/flash-1.png",
  },
];
export const TopCategoriesData = [
  {
    id: 5,
    category: "Headphone",
    imageAddress: "/image/category-1.png",
  },
  {
    id: 6,
    category: "Watch",
    imageAddress: "/image/category-2.png",
  },
  {
    id: 7,
    category: "Sunglass",
    imageAddress: "/image/category-3.png",
  },
  {
    id: 8,
    category: "Headphone",
    imageAddress: "/image/category-1.png",
  },
  {
    id: 9,
    category: "Watch",
    imageAddress: "/image/category-2.png",
  },
  {
    id: 10,
    category: "Sunglass",
    imageAddress: "/image/category-3.png",
  },
];
export const TopRatingsData = [
  {
    id: 11,
    imageAddress: "/image/camera-1.png",
    star: 4,
    numberPeople: 49,
    name: "Camera",
    price: 3.3,
  },
  {
    id: 12,
    imageAddress: "/image/shoes-2.png",
    star: 5,
    numberPeople: 20,
    name: "Shoe",
    price: 400,
  },
  {
    id: 13,
    imageAddress: "/image/mobile-1.png",
    star: 5,
    numberPeople: 65,
    name: "Phone",
    price: 999,
  },
  {
    id: 14,
    imageAddress: "/image/watch-1.png",
    star: 5,
    numberPeople: 75,
    name: "Watch",
    price: 999,
  },
];
export const NewArrivalsData = [
  {
    id: 15,
    imageAddress: "/image/imagegoggles (1).png",
    title: "Sunglass",
    price: 150,
  },
  {
    id: 16,
    imageAddress: "/image/lipstick (2) (1).png",
    title: "Makeup",
    price: 250,
  },
  {
    id: 17,
    imageAddress: "/image/bgwatch (1).png",
    title: "Smart Watch",
    price: 350,
  },
  {
    id: 18,
    imageAddress: "/image/bgwatch (1).png",
    title: "Lipstick",
    price: 15,
  },
  {
    id: 19,
    imageAddress: "/image/lipstick (4) (1).png",
    title: "Green Plant",
    price: 55,
  },
  {
    id: 20,
    imageAddress: "/image/lipstick (3) (1).png",
    title: "Bonsai tree",
    price: 535,
  },
];
export const BigDiscountsData = [
  { id: 21, imageAddress: "/image/7.png", title: "BenX 2020", price: 233 },
  { id: 22, imageAddress: "/image/9.png", title: "Tony TV 1080p", price: 278 },
  { id: 23, imageAddress: "/image/10.png", title: "Tony PS4", price: 177 },
  { id: 24, imageAddress: "/image/11.png", title: "Setgearr 2020", price: 124 },
  { id: 25, imageAddress: "/image/12.png", title: "Tony BGB", price: 284 },
  { id: 26, imageAddress: "/image/13.png", title: "RG products", price: 300 },
  {
    id: 27,
    imageAddress: "/image/14.png",
    title: "Ranasonic 2019",
    price: 137,
  },
  { id: 28, imageAddress: "/image/15.png", title: "Pune HD", price: 111 },
  { id: 29, imageAddress: "/image/16.png", title: "Tony CCTV", price: 150 },
];
export const CarsData = [
  {
    id: 30,
    off: 8,
    name: "Lord 2019",
    star: 2,
    price: 154.56,
    discount: 168.0,
    imageAddress: "/image/1.png",
  },
  {
    id: 31,
    off: 6,
    name: "Budi 2017",
    star: 3,
    price: 212.44,
    discount: 315.0,
    imageAddress: "/image/2.png",
  },
  {
    id: 32,
    off: 10,
    name: "Resla 2015",
    star: 4,
    price: 90.9,
    discount: 101.0,
    imageAddress: "/image/3.png",
  },
  {
    id: 33,
    off: 7,
    name: "Xorsch 2018",
    star: 2,
    price: 224.13,
    discount: 241.0,
    imageAddress: "/image/4.png",
  },
  {
    id: 34,
    off: 7,
    name: "Lord 2018",
    star: 5,
    price: 215.12,
    discount: 236.0,
    imageAddress: "/image/5.png",
  },
  {
    id: 35,
    off: 6,
    name: "Lord 2020",
    star: 2,
    price: 109.98,
    discount: 117.0,
    imageAddress: "/image/6.png",
  },
];
